"""Real-parts catalog (generated by scripts/build_catalog.py).

Loads catalog.json — curated architecture parts, the validated LEGO colour
palette (classic/full tiers), and per-part colour availability proven by
Rebrickable's elements.csv ("a real mould exists in this colour").

Everything degrades gracefully: if catalog.json is missing the loaders return
None/empty and the legolizer falls back to its built-in starter palette.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

_CATALOG_PATH = Path(__file__).resolve().parent / "catalog.json"


@lru_cache(maxsize=1)
def load_catalog() -> Optional[dict[str, Any]]:
    try:
        return json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


@lru_cache(maxsize=4)
def get_palette(tier: str = "classic") -> Optional[list[tuple[int, str, tuple[int, int, int]]]]:
    """Palette in the legolizer's native shape: (LDraw code, name, sRGB)."""
    cat = load_catalog()
    if not cat:
        return None
    codes = cat.get("palettes", {}).get(tier)
    if not codes:
        return None
    by_code = {c["code"]: c for c in cat["colors"]}
    out = []
    for code in codes:
        c = by_code.get(code)
        if c:
            out.append((c["code"], c["name"], tuple(c["rgb"])))
    return out or None


@lru_cache(maxsize=1)
def part_colors() -> dict[str, frozenset[int]]:
    """Per part id: the set of LDraw colour codes a real element exists in."""
    cat = load_catalog()
    if not cat:
        return {}
    return {pid: frozenset(codes) for pid, codes in cat.get("part_colors", {}).items()}


@lru_cache(maxsize=1)
def parts_by_id() -> dict[str, dict[str, Any]]:
    cat = load_catalog()
    if not cat:
        return {}
    return {p["id"]: p for p in cat.get("parts", [])}


def parts_in_family(family: str, placeable_only: bool = True) -> list[dict[str, Any]]:
    return [
        p for p in parts_by_id().values()
        if p["family"] == family and (p.get("place", True) or not placeable_only)
    ]


def attribution() -> str:
    cat = load_catalog()
    return (cat or {}).get("attribution", "")
